enable_color: true
rgb_camera.color_profile: 1280x720x30
enable_depth: true
depth_module.depth_profile: 1280x720x30
align_depth.enable: true
enable_sync: true
publish_tf: true
tf_publish_rate: 1.0
pointcloud.enable: true
