device_type: D455
enable_color: false
enable_depth: true
depth_module.depth_profile: 480x270x15
enable_sync: true
publish_tf: true
pointcloud.enable: false
align_depth.enable: false
spatial_filter.enable: false
temporal_filter.enable: false
hole_filling_filter.enable: false
enable_infra: false
enable_infra1: false
enable_infra2: false
